# Generated by Django 6.0.3 on 2026-03-13 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivoapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correctivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código PDS')),
                ('descripcion', models.TextField(verbose_name='Descripción de la avería')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha inicio')),
                ('hora_inicio', models.TimeField(auto_now_add=True, verbose_name='Hora inicio')),
                ('tiempo', models.DurationField(blank=True, null=True, verbose_name='Tiempo transcurrido')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin')),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('en_reparacion', 'En reparación'), ('finalizado', 'Finalizado')], default='iniciado', max_length=20, verbose_name='Estado')),
                ('automatismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctivos', to='preventivoapp.automatismo')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correctivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correctivo',
                'verbose_name_plural': 'Correctivos',
                'ordering': ['-fecha_inicio', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DeficienciaCorrectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('electrica', 'Eléctrica'), ('mecanica', 'Mecánica'), ('neumatica', 'Neumática'), ('hidraulica', 'Hidráulica'), ('software', 'Software'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20, verbose_name='Severidad')),
                ('correctivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deficiencias', to='preventivoapp.correctivo')),
            ],
            options={
                'verbose_name': 'Deficiencia',
                'verbose_name_plural': 'Deficiencias',
            },
        ),
        migrations.CreateModel(
            name='FotoCorrectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_correctivo/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('correctivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='preventivoapp.correctivo')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='RecambioCorrectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del recambio')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('correctivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recambios', to='preventivoapp.correctivo')),
            ],
            options={
                'verbose_name': 'Recambio',
                'verbose_name_plural': 'Recambios',
            },
        ),
    ]
