# Generated by Django 6.0.3 on 2026-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivoapp', '0002_correctivo_deficienciacorrectivo_fotocorrectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctivo',
            name='hora_parada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de última parada'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='hora_parada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de última parada'),
        ),
        migrations.AlterField(
            model_name='correctivo',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_reparacion', 'En reparación'), ('parado', 'Parado'), ('finalizado', 'Finalizado')], default='iniciado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_progreso', 'En curso'), ('parado', 'Parado'), ('finalizado', 'Finalizado')], default='iniciado', max_length=20, verbose_name='Estado'),
        ),
    ]
