# Generated by Django 6.0.3 on 2026-03-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivoapp', '0003_correctivo_hora_parada_preventivo_hora_parada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='fotocorrectivo',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
    ]
