# Generated by Django 6.0.3 on 2026-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivoapp', '0004_alter_foto_imagen_alter_fotocorrectivo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.URLField(verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='fotocorrectivo',
            name='imagen',
            field=models.URLField(verbose_name='Imagen'),
        ),
    ]
